export const COURSES = [
  'PREESCOLAR LIBERTADOR MAÑANA',
  'PRIMERO LIBERTADOR MAÑANA',
  'SEGUNDO LIBERTADOR MAÑANA',
  'TERCERO LIBERTADOR MAÑANA',
  'CUARTO LIBERTADOR MAÑANA',
  'QUINTO LIBERTADOR MAÑANA',
  'C601',
  'C602',
  'C701',
  'C702',
  'C703',
  'C801',
  'C802',
  'C901',
  'C902',
  'C1001',
  'C1101',
]

export const LIBERTADOR_MORNING = { colegio: 'LIBERTADORES', jornada: 'TARDE' }
