export const SET_COURSES = 'SET_COURSES'
export const SET_SHEETS = 'SET_SHEETS'
export const SET_FULL_DATA = 'SET_FULL_DATA'
export const GET_COURSE = 'GET_COURSE'
export const GET_NOTES_COURSE = 'GET_NOTES_COURSE'
export const SET_ERROR = 'SET_ERROR'
