import Head from 'next/head'
import Router from 'next/router'
import { Header } from 'components/header'
import { Sidebar } from 'components/sidebar'
import { Loader } from 'components/loader'
import { useSelector } from 'react-redux'
import { TOKEN } from 'constants/Auth'
import { useEffect } from 'react'

export const Layout = ({ children }) => {
  const { showLoader } = useSelector(state => state.loader)

  const isAuthenticated = !!localStorage[TOKEN]

  useEffect(() => {
    if (window.location.pathname !== '/' && !isAuthenticated) Router.push('/')
  }, [])

  return (
    <div className="flex flex-col h-screen">
      <Head>
        <title>Conecta edu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css"
          integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g=="
          crossOrigin="anonymous"
          referrerPolicy="no-referrer"
        />
      </Head>
      <main className="flex flex-1">
        {showLoader && <Loader />}
        {isAuthenticated && <Sidebar />}
        <div className="flex flex-col flex-1">
          <Header />
          <div className="flex-1 p-6" style={{ background: '#e3e5e6' }}>
            {children}
          </div>
        </div>
      </main>
    </div>
  )
}
