// import Head from 'next/head'
// import { Header } from 'components/header'
// import { Sidebar } from 'components/sidebar'

// export const Layout = ({ children }) => {
//   return (
//     <div className="flex flex-col h-screen">
//       <Head>
//         <title>Conecta edu</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/favicon.ico" />
//         <link
//           rel="stylesheet"
//           href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css"
//           integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g=="
//           crossOrigin="anonymous"
//           referrerPolicy="no-referrer"
//         />
//       </Head>
//       <main className="flex h-full flex-1">
//         <Sidebar />
//         <div className="flex-1">{children}</div>
//       </main>
//     </div>
//   )
// }

// import Head from 'next/head'
// import { Header } from 'components/header'
// import { Sidebar } from 'components/sidebar'

// export const Layout = ({ children }) => {
//   return (
//     <div className="flex flex-col h-screen">
//       <Head>
//         <title>Conecta edu</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/favicon.ico" />
//         <link
//           rel="stylesheet"
//           href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css"
//           integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g=="
//           crossOrigin="anonymous"
//           referrerPolicy="no-referrer"
//         />
//       </Head>
//       <Header />
//       <main className="flex h-full flex-1">
//         <Sidebar />
//         <div className="flex-1">{children}</div>
//       </main>
//     </div>
//   )
// }

import Head from 'next/head'
import { Header } from 'components/header'
import { Sidebar } from 'components/sidebar'
import { Loader } from 'components/loader'
import { useSelector } from 'react-redux'

export const Layout = ({ children }) => {
  const { showLoader } = useSelector(state => state.loader)

  return (
    <div className="flex flex-col h-screen">
      <Head>
        <title>Conecta edu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css"
          integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g=="
          crossOrigin="anonymous"
          referrerPolicy="no-referrer"
        />
      </Head>
      <main className="flex h-full flex-1">
        {showLoader && <Loader />}
        <Sidebar />
        <div className="flex flex-col flex-1">
          <Header />
          <div className="flex-1" style={{ background: '#e3e5e6' }}>
            {children}
          </div>
        </div>
      </main>
    </div>
  )
}
