import { useEffect } from 'react'
import { ToastContainer } from 'react-toastify'
import { useDispatch, useSelector } from 'react-redux'
import Head from 'next/head'
import Router, { useRouter } from 'next/router'
import { Header } from 'components/header'
import { Sidebar } from 'components/sidebar'
import { Loader } from 'components/loader'
import { isValidToken } from 'utils/Token'
import { setLoaderStatus } from 'redux/loader/actions'
import 'react-toastify/dist/ReactToastify.css'

export const UNPROTECTED_ROUTES = ['/', '/iniciar-sesion']

export const Layout = ({ children }) => {
  const dispatch = useDispatch()
  const { push, pathname } = useRouter()
  const { showLoader } = useSelector(state => state.loader)

  useEffect(() => {
    validateSession()
  }, [])

  const validateSession = () => {
    if (UNPROTECTED_ROUTES.includes(pathname)) return
    if (!isValidToken()) {
      push('/')
      dispatch(setLoaderStatus(false))
    }
  }

  return (
    <div className="flex flex-col h-screen">
      <Head>
        <title>Conecta EDU</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css"
          integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g=="
          crossOrigin="anonymous"
          referrerPolicy="no-referrer"
        />
      </Head>
      <main className="flex flex-1">
        <ToastContainer />
        {showLoader && <Loader />}
        {isValidToken() && <Sidebar />}
        <div className="flex flex-col flex-1">
          <Header />
          <div className="flex-1 p-6" style={{ background: '#e3e5e6' }}>
            {children}
          </div>
        </div>
      </main>
    </div>
  )
}
