export const URLS = {
  images: 'https://api.conectaedu.co/public/files/',
  getSubjects: 'get-courses',
  getStudents: 'get-achievements',
  getCompleteStudents: 'getfullStudents',
  getCourses: 'get-cohorts',
  getCourse: cohort => `course-info?id=${cohort}`,
  getStudentsByCohort: cohort => `get-getstudentbycohorts?cohort=${cohort}`,
  getCoursesByCohort: cohort => `get-getcoursesbycohorts?cohort=${cohort}`,
  getSheets: 'getfulldata',
  getFullData: 'getfulldataByReport',
  getCohort: 'get-cohorts',
  getObservations: 'observations',
  getStudentUser: 'student',
  getReport: 'getreport',
  postInstitution: 'institution-info',
  updateInstitution: 'institution-info-update/1',
  updateCourse:'update-course',
  getInstitutions: 'institution-info',
  assets: institution => `/assets/${institution}`,
}
