export const URLS = {
  getSubjects: 'get-courses',
  getStudents: 'get-achievements',
  getStudentInformation: 'get-info-student',
  getCompleteStudents: 'getfullStudents',
  getCourses: 'get-cohorts',
  getStudentsByCohort: cohort => `get-getstudentbycohorts?cohort=${cohort}`,
  getCoursesByCohort: 'get-getcoursesbycohorts',
  getStudentScores: 'getfulldata',
  getSheets: 'getfulldata',
  getFullData: 'getfulldataByReport',
  getCohort: 'get-cohorts',
  getObservations: 'observations',
  getStudentUser: 'student',
}
